main: dev.tallenpeli.serverHomes.ServerHomes
name: ServerHomes
version: 0.0.3-Beta
api-version: 1.21

commands:
  home:
    description: Teleport to your set home
    usage: /home <name>
    permission: tallenpeli.serverHomes.home
    permission-message: §cYou don't have permission to use the home command!
  homes:
    description: List all your homes
    usage: /homes
    permission: tallenpeli.serverHomes.homes
    permission-message: §cYou don't have permission to use the homes command!
  sethome:
    description: Set your home
    usage: /sethome <name>
    permission: tallenpeli.serverHomes.sethome
    permission-message: §cYou don't have permission to use the sethome command!
  delhome:
    description: Set your home
    usage: /delhome <name>
    permission: tallenpeli.serverHomes.delhome
    permission-message: §cYou don't have permission to use the delhome command!
  confirm:
    description: Confirm a home deletion
    usage: /confirm
    permission: tallenpeli.serverHomes.confirm
    permission-message: §cYou don't have permission to use the confirm command!
  cancel:
    description: Cancels a confirmation request
    usage: /cancel
    permission: tallenpeli.serverHomes.cancel
    permission-message: §cYou don't have permission to use the cancel command!

permissions:
  tallenpeli.serverHomes.home:
    description: Teleports you to your home.
    default: true
  tallenpeli.serverHomes.sethome:
    description: Sets the player's home.
    default: true
  tallenpeli.serverHomes.delhome:
    description: Delete a specified home.
    default: true
  tallenpeli.serverHomes.confirm:
    description: Confirm a home deletion.
    default: true
  tallenpeli.serverHomes.cancel:
    description: Cancel a pending confirmation.
    default: true
  tallenpeli.serverHomes.homes:
    description: Lists all your homes.
    default: true

  tallenpeli.serverHomes.cooldown.bypass:
    description: Allows certain players to bypass the teleport cooldown.
    default: op
  tallenpeli.serverHomes.delay.bypass:
    description: Allows certain players to bypass the teleport delay (timer).
    default: op
  tallenpeli.serverHomes.confirm.bypass:
    description: Allows certain players to skip all confirmation prompts.
    default: op
  tallenpeli.serverHomes.limit.vip:
    description: Grants the player the higher home limit (max_homes_vip).
    default: false